# Generated by Django 5.2.13 on 2026-04-28 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='vehiclereview',
            options={'ordering': ['-created_at']},
        ),
    ]
