# Generated by Django 5.2.13 on 2026-04-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_vehicle_options_alter_vehiclereview_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='quantity_available',
            field=models.IntegerField(default=1, help_text='Number of vehicles available'),
        ),
    ]
